var l=window.location.href;0==l.indexOf("http://118.26.238.100")||0==l.indexOf("http://192.168.1.200")||(window.location.href="http://118.26.238.100/game/blockgogogo");
var WeixinApi=function(){return{version:"1.8",ready:function(b){if(b&&"function"==typeof b){var a=this,c=function(){b(a)};"undefined"==typeof window.WeixinJSBridge?document.addEventListener?document.addEventListener("WeixinJSBridgeReady",c,!1):document.attachEvent&&(document.attachEvent("WeixinJSBridgeReady",c),document.attachEvent("onWeixinJSBridgeReady",c)):c()}},shareToTimeline:function(b,a){a=a||{};var c=function(b){WeixinJSBridge.invoke("shareTimeline",{appid:b.appId?b.appId:"",img_url:b.imgUrl,
link:b.link,desc:b.title,title:b.desc,img_width:"120",img_height:"120"},function(b){switch(b.err_msg){case "share_timeline:cancel":a.cancel&&a.cancel(b);break;case "share_timeline:fail":a.fail&&a.fail(b);break;case "share_timeline:confirm":case "share_timeline:ok":a.confirm&&a.confirm(b)}a.all&&a.all(b)})};WeixinJSBridge.on("menu:share:timeline",function(d){a.async&&a.ready?(window._wx_loadedCb_=a.dataLoaded||new Function,0<window._wx_loadedCb_.toString().indexOf("_wx_loadedCb_")&&(window._wx_loadedCb_=
new Function),a.dataLoaded=function(a){window._wx_loadedCb_(a);c(a)},a.ready&&a.ready(d)):(a.ready&&a.ready(d),c(b))})},shareToWeibo:function(b,a){a=a||{};var c=function(b){WeixinJSBridge.invoke("shareWeibo",{content:b.desc,url:b.link},function(b){switch(b.err_msg){case "share_weibo:cancel":a.cancel&&a.cancel(b);break;case "share_weibo:fail":a.fail&&a.fail(b);break;case "share_weibo:confirm":case "share_weibo:ok":a.confirm&&a.confirm(b)}a.all&&a.all(b)})};WeixinJSBridge.on("menu:share:weibo",function(d){a.async&&
a.ready?(window._wx_loadedCb_=a.dataLoaded||new Function,0<window._wx_loadedCb_.toString().indexOf("_wx_loadedCb_")&&(window._wx_loadedCb_=new Function),a.dataLoaded=function(a){window._wx_loadedCb_(a);c(a)},a.ready&&a.ready(d)):(a.ready&&a.ready(d),c(b))})},shareToFriend:function(b,a){a=a||{};var c=function(b){WeixinJSBridge.invoke("sendAppMessage",{appid:b.appId?b.appId:"",img_url:b.imgUrl,link:b.link,desc:b.desc,title:b.title,img_width:"120",img_height:"120"},function(b){switch(b.err_msg){case "send_app_msg:cancel":a.cancel&&
a.cancel(b);break;case "send_app_msg:fail":a.fail&&a.fail(b);break;case "send_app_msg:confirm":case "send_app_msg:ok":a.confirm&&a.confirm(b)}a.all&&a.all(b)})};WeixinJSBridge.on("menu:share:appmessage",function(d){a.async&&a.ready?(window._wx_loadedCb_=a.dataLoaded||new Function,0<window._wx_loadedCb_.toString().indexOf("_wx_loadedCb_")&&(window._wx_loadedCb_=new Function),a.dataLoaded=function(a){window._wx_loadedCb_(a);c(a)},a.ready&&a.ready(d)):(a.ready&&a.ready(d),c(b))})},showOptionMenu:function(){WeixinJSBridge.call("showOptionMenu")},
hideOptionMenu:function(){WeixinJSBridge.call("hideOptionMenu")},showToolbar:function(){WeixinJSBridge.call("showToolbar")},hideToolbar:function(){WeixinJSBridge.call("hideToolbar")},getNetworkType:function(b){b&&"function"==typeof b&&WeixinJSBridge.invoke("getNetworkType",{},function(a){b(a.err_msg)})},imagePreview:function(b,a){b&&(a&&0!=a.length)&&WeixinJSBridge.invoke("imagePreview",{current:b,urls:a})},closeWindow:function(){WeixinJSBridge.call("closeWindow")}}}(),wxData={appId:"",imgUrl:"http://118.26.238.100/quyou/appshow/img/block.png",
link:"http://118.26.238.100/game/blockgogogo/",desc:"\u65b9\u5757\u51b2\u51b2\u51b2\uff0c\u7b80\u5355\u6709\u8da3\u7684\u5c0f\u6e38\u620f\uff0c\u8d76\u5feb\u6765\u6311\u6218\u5427!",_desc:"\u65b9\u5757\u51b2\u51b2\u51b2\uff0c\u7b80\u5355\u6709\u8da3\u7684\u5c0f\u6e38\u620f\uff0c\u8d76\u5feb\u6765\u6311\u6218\u5427!",title:"Block Go!Go!Go!"};
WeixinApi.ready(function(b){var a={ready:function(){},cancel:function(a){},fail:function(a){},confirm:function(a){},all:function(a){}};b.shareToFriend(wxData,a);b.shareToTimeline(wxData,a);b.shareToWeibo(wxData,a)});
var isWeChat=function(){return"micromessenger"==navigator.userAgent.toLowerCase().match(/MicroMessenger/i)?!0:!1},flyfishShare={show:function(){document.querySelector(".bg").style.display="block";var b=document.querySelector("#Cocos2dGameContainer"),a=document.querySelector("#flyfishShareDom"),c=document.querySelector("#flyfishArrowDom");a||(a=document.createElement("div"),a.id="flyfishShareDom",a.innerHTML="\x3cdiv id\x3d'more' class\x3d'shareItem'\x3e                \x3c/div\x3e                \x3cdiv class\x3d'shareItem' onclick\x3d'flyfishShare.more()'\x3e                    \u66f4\u591a\u6e38\u620f                \x3c/div\x3e                \x3cdiv class\x3d'shareItem' onclick\x3d'flyfishShare.back()'\x3e                    \u8fd4\u56de                \x3c/div\x3e",
b.appendChild(a),isWeChat()&&(c=document.createElement("div"),c.id="flyfishArrowDom",c.innerHTML='\x3cimg src\x3d"res/arrow.png"\x3e\x3cdiv class\x3d"desc"\x3e\u8bf7\u70b9\u51fb\u53f3\u4e0a\u89d2\u7684\u83dc\u5355\u6309\u94ae\x3cbr /\x3e\u518d\u70b9\u201c\u5206\u4eab\u5230\u670b\u53cb\u5708\u201d\x3cbr /\x3e\u8ba9\u597d\u53cb\u4eec\u6765\u6311\u6218\u5427\uff01\x3c/div\x3e',b.appendChild(c),c.style.display="block"),b=document.querySelector("#jiathis"),c=document.querySelector("#more"),b.style.display=
"block",c.appendChild(b));a.style.display="block"},back:function(){this.close();cc.director.runScene(cc.TransitionFade.create(0.5,new GameScene))},close:function(){var b=document.querySelector("#flyfishShareDom"),a=document.querySelector("#flyfishArrowDom");b&&(b.style.display="none",a&&(a.style.display="none"));document.querySelector(".bg").style.display="none"},more:function(){window.open("http://118.26.238.100/flyfish/appshow/")}};